version: "3.9"

services:
    # 🧠 PHP-FPM (Laravel backend)
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        env_file:
            - .env
        restart: always
        networks:
            - default

    # 🌐 Nginx для Laravel
    web:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        container_name: laravel_web
        expose:
            - "80" # не пробрасываем наружу — общение только через reverse-proxy
        environment:
            - VIRTUAL_HOST=assistant.tumanov.group
            - LETSENCRYPT_HOST=assistant.tumanov.group
            - LETSENCRYPT_EMAIL=admin@tumanov.group
        depends_on:
            - app
        volumes:
            - .:/var/www/html
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        restart: always
        networks:
            - default
            - www_default # сеть reverse-proxy

    # 🗄️ MySQL
    db:
        image: mysql:8.0
        container_name: laravel_db
        ports:
            - "3306:3306"
        restart: always
        env_file:
            - .env.docker
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - default

volumes:
    db_data:

networks:
    default:
        driver: bridge

    www_default: # внешняя сеть nginx-proxy
        external: true
