version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        env_file:
            - .env

    web:
        build:
            context: .
            dockerfile: Dockerfile.nginx   # отдельный Dockerfile для nginx+certbot
        container_name: laravel_web
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/letsencrypt:/etc/letsencrypt
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: laravel_db
        ports:
            - "3306:3306"
        restart: always
        env_file:
            - .env.docker
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
