version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        env_file:
            - .env   # Laravel конфиг

    web:
        image: nginx:stable
        container_name: laravel_web
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: always
        env_file:
            - .env.docker  # настройки только для MySQL
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
